In [65]:
import lightgbm as lgb 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import DataFrame as df
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from time import time
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score    


In [27]:
Total_datas = pd.read_csv('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/실험데이터/Total_datas.csv', names = ['a-b','c-d'])
Total_labels = pd.read_csv('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/실험데이터/Total_labels.csv',names=['Gesture'])


In [171]:
X_train, X_test, y_train, y_test = train_test_split(Total_datas, Total_labels, test_size=0.3, random_state=10)

In [183]:
model = lgb.LGBMClassifier(boosting_type='gbdt', 
                 objective='multiclass', num_class=4,num_leaves=500,
                 num_iteration=300, max_depth=15, learning_rate=0.02, 
                 n_estimators=100, nthread=10, silent=False)

lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train)

In [184]:
cv_results = cross_val_score(model, X_train, y_train, 
                   cv = 2, scoring='accuracy', n_jobs = -1, verbose = 1)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:  2.5min finished


In [185]:
model.fit(X_train, y_train)

C:\Users\hml76\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hml76\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hml76\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\engine.py:148: UserWarning: Found `num_iteration` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.02, max_depth=15,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, nthread=10, num_class=4,
               num_iteration=300, num_leaves=500, objective='multiclass',
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=False,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [186]:
y_pred=model.predict(X_test)

In [187]:
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7221656846991609


In [188]:
print(); print(cv_results)    
print(); print(model)


[0.7208781  0.71937745]

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.02, max_depth=15,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, nthread=10, num_class=4,
               num_iteration=300, num_leaves=500, objective='multiclass',
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=False,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)


In [189]:
y_pred = model.predict(X_test)

In [190]:
print(); print(metrics.classification_report(y_test, y_pred))
print(); print(metrics.confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.58      0.53      0.55     16791
           1       0.76      0.71      0.73     23927
           2       0.70      0.77      0.73     29339
           3       0.77      0.78      0.77     41963

    accuracy                           0.72    112020
   macro avg       0.70      0.69      0.70    112020
weighted avg       0.72      0.72      0.72    112020


[[ 8832  1285  4799  1875]
 [ 1561 16994  1640  3732]
 [ 2055   678 22499  4107]
 [ 2691  3371  3329 32572]]


In [194]:
Total_labels

Gesture
0             0
1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             0
10            0
11            0
12            0
13            0
14            0
15            0
16            0
17            0
18            0
19            0
20            0
21            0
22            0
23            0
24            0
25            0
26            0
27            0
28            0
29            0
...         ...
373370        3
373371        3
373372        3
373373        3
373374        3
373375        3
373376        3
373377        3
373378        3
373379        3
373380        3
373381        3
373382        3
373383        3
373384        3
373385        3
373386        3
373387        3
373388        3
373389        3
373390        3
373391        3
373392        3
373393        3
373394        3
373395        3
373396        3
373397        3
373398        3
373399        3

[373400 rows x 1 columns]

In [61]:
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=20,
                valid_sets=lgb_eval,
                early_stopping_rounds=5)

[1]	valid_0's multi_logloss: 1.24511
Training until validation scores don't improve for 5 rounds
[2]	valid_0's multi_logloss: 1.17385
[3]	valid_0's multi_logloss: 1.11398
[4]	valid_0's multi_logloss: 1.06291
[5]	valid_0's multi_logloss: 1.01883
[6]	valid_0's multi_logloss: 0.980515
[7]	valid_0's multi_logloss: 0.947083
[8]	valid_0's multi_logloss: 0.917764
[9]	valid_0's multi_logloss: 0.89192
[10]	valid_0's multi_logloss: 0.869116
[11]	valid_0's multi_logloss: 0.848932
[12]	valid_0's multi_logloss: 0.830979
[13]	valid_0's multi_logloss: 0.814977
[14]	valid_0's multi_logloss: 0.800645
[15]	valid_0's multi_logloss: 0.787814
[16]	valid_0's multi_logloss: 0.776356
[17]	valid_0's multi_logloss: 0.766089
[18]	valid_0's multi_logloss: 0.756845
[19]	valid_0's multi_logloss: 0.748523
[20]	valid_0's multi_logloss: 0.740986
Did not meet early stopping. Best iteration is:
[20]	valid_0's multi_logloss: 0.740986


In [62]:
y_pred = gbm.predict(X_test,reshape = True)
from sklearn import metrics
y_pred[0:1000]

array([[0.03399697, 0.06510992, 0.06281822, 0.83807489],
       [0.03188107, 0.05982918, 0.05890856, 0.84938119],
       [0.03106191, 0.06506408, 0.05816048, 0.84571353],
       ...,
       [0.04416071, 0.04753373, 0.83851803, 0.06978753],
       [0.1341504 , 0.11167376, 0.07266577, 0.68151008],
       [0.0389031 , 0.05733929, 0.28359734, 0.62016028]])

In [ ]:
for i in range(len(X_)):
    if ypred2[i]>=.5:       # setting threshold to .5
       ypred2[i]=1
    else:  
       ypred2[i]=0

In [42]:
print("훈련 세트 정확도: {:.3f}".format(gbm.score(X_train, y_train)))
print("테스트 세트 정확도: {:.3f}".format(gbm.score(X_test, y_test)))
print("테스트 세트 정확도: {:.3f}".format(gbm.score(y_test,y_pred)))

AttributeError: 'Booster' object has no attribute 'score'

In [43]:
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets

In [ ]:
print('Save model...')
# save model to file
gbm.save_model('model.txt')
