In [13]:
import lightgbm as lgb 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import DataFrame as df
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from time import time
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score    
from sklearn import metrics


In [2]:
Total_datas_new = pd.read_csv('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/실험데이터/Total_datas_with_merged.csv')
Total_labels_new = pd.read_csv('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/실험데이터/Total_labels_with_merged.csv')

In [4]:
X_train, X_test, y_train, y_test = train_test_split(Total_datas_new, Total_labels_new, test_size=0.3, random_state=10)

In [5]:
model = lgb.LGBMClassifier(boosting_type='gbdt', 
                 objective='multiclass', num_class=4,num_leaves=500,
                 num_iteration=300, max_depth=15, learning_rate=0.02, 
                 n_estimators=100, nthread=10, silent=False)

lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train)

In [6]:
cv_results = cross_val_score(model, X_train, y_train, 
                   cv = 2, scoring='accuracy', n_jobs = -1, verbose = 1)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:  4.7min finished


In [7]:
model.fit(X_train, y_train)

C:\Users\hml76\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hml76\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hml76\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\engine.py:148: UserWarning: Found `num_iteration` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.02, max_depth=15,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, nthread=10, num_class=4,
               num_iteration=300, num_leaves=500, objective='multiclass',
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=False,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [8]:
y_pred=model.predict(X_test)

In [12]:
print("훈련 세트 정확도: {:.3f}".format(model.score(X_train, y_train)))
print("테스트 세트 정확도: {:.3f}".format(model.score(X_test, y_test)))

훈련 세트 정확도: 0.885
테스트 세트 정확도: 0.856


In [14]:
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8563100902525465


In [15]:
print(); print(cv_results)    
print(); print(model)


[0.85093619 0.85116347]

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.02, max_depth=15,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, nthread=10, num_class=4,
               num_iteration=300, num_leaves=500, objective='multiclass',
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=False,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)


In [16]:
y_pred = model.predict(X_test)

In [17]:
print(); print(metrics.classification_report(y_test, y_pred))
print(); print(metrics.confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.79      0.72      0.75     16793
           1       0.89      0.87      0.88     23943
           2       0.82      0.89      0.85     29337
           3       0.88      0.89      0.88     41946

    accuracy                           0.86    112019
   macro avg       0.85      0.84      0.84    112019
weighted avg       0.86      0.86      0.86    112019


[[12080   389  3335   989]
 [  586 20745   559  2053]
 [ 1152   426 25974  1785]
 [ 1484  1692  1646 37124]]


In [61]:
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=20,
                valid_sets=lgb_eval,
                early_stopping_rounds=5)

[1]	valid_0's multi_logloss: 1.24511
Training until validation scores don't improve for 5 rounds
[2]	valid_0's multi_logloss: 1.17385
[3]	valid_0's multi_logloss: 1.11398
[4]	valid_0's multi_logloss: 1.06291
[5]	valid_0's multi_logloss: 1.01883
[6]	valid_0's multi_logloss: 0.980515
[7]	valid_0's multi_logloss: 0.947083
[8]	valid_0's multi_logloss: 0.917764
[9]	valid_0's multi_logloss: 0.89192
[10]	valid_0's multi_logloss: 0.869116
[11]	valid_0's multi_logloss: 0.848932
[12]	valid_0's multi_logloss: 0.830979
[13]	valid_0's multi_logloss: 0.814977
[14]	valid_0's multi_logloss: 0.800645
[15]	valid_0's multi_logloss: 0.787814
[16]	valid_0's multi_logloss: 0.776356
[17]	valid_0's multi_logloss: 0.766089
[18]	valid_0's multi_logloss: 0.756845
[19]	valid_0's multi_logloss: 0.748523
[20]	valid_0's multi_logloss: 0.740986
Did not meet early stopping. Best iteration is:
[20]	valid_0's multi_logloss: 0.740986


In [62]:
y_pred = gbm.predict(X_test,reshape = True)
from sklearn import metrics
y_pred[0:1000]

array([[0.03399697, 0.06510992, 0.06281822, 0.83807489],
       [0.03188107, 0.05982918, 0.05890856, 0.84938119],
       [0.03106191, 0.06506408, 0.05816048, 0.84571353],
       ...,
       [0.04416071, 0.04753373, 0.83851803, 0.06978753],
       [0.1341504 , 0.11167376, 0.07266577, 0.68151008],
       [0.0389031 , 0.05733929, 0.28359734, 0.62016028]])

In [ ]:
print('Save model...')
# save model to file
gbm.save_model('model.txt')
