In [1]:
import glob
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import DataFrame as df
import seaborn as sns


from keras.layers import LSTM, Dense
from keras.models import Sequential
import keras.backend as K
from keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, EarlyStopping
from keras.optimizers import Adam
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import KFold, cross_val_score

from sklearn.model_selection import train_test_split

Using TensorFlow backend.
C:\Users\hml76\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\hml76\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\hml76\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users

In [2]:
data_1 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/LR/*.csv')
data_1_2 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/LR2/*.csv')

data_2 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/RL/*.csv')
data_2_2 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/RL2/*.csv')

data_3 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/CW/*.csv')
data_3_2 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/CW2/*.csv')

data_4 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/CCW/*.csv')
data_4_2 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/CCW2/*.csv')

data_5 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/DOWN/*.csv')
data_5_2 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/DOWN2/*.csv')

data_6 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/UP/*.csv')
data_6_2 = glob.glob('C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/UP2/*.csv')



len(data_1),len(data_1_2), len(data_2),len(data_2_2), len(data_3),len(data_3_2), len(data_4),len(data_4_2), len(data_5),len(data_5_2), len(data_6), len(data_6_2)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [3]:
total_data_2 = data_1 + data_1_2 + data_2 + data_2_2 + data_3 + data_3_2 + data_4 + data_4_2 + data_5 + data_5_2 + data_6 + data_6_2 
total_data = data_1 + data_2 + data_3 + data_4 + data_5 + data_6 
total_data_1 = data_1_2 + data_2_2 + data_3_2 + data_4_2 + data_5_2 + data_6_2 


dataset_2 = np.zeros((len(total_data_2), 100, 6))
dataset_1 = np.zeros((len(total_data_1), 100, 6))
dataset = np.zeros((len(total_data), 100, 6))

dataset

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        .

In [4]:
for i, data in enumerate(total_data):
    #print(data)
    dataset[i] = pd.read_csv(data, names=['n','na','a','b','c','d','a-b','c-d']).sample(n=100).sort_index().iloc[:,:6]
    
    
label = np.array([[1, 0, 0 ,0, 0, 0 ]] * len(data_1) + [[0, 1, 0, 0, 0, 0 ]] * len(data_2) + [[0, 0, 1, 0, 0, 0 ]] * len(data_3) + [[0, 0, 0, 1, 0, 0 ]] * len(data_4) + [[0, 0, 0, 0, 1, 0 ]] * len(data_5) + [[0, 0, 0, 0, 0, 1]] * len(data_6))
dataset.shape, label.shape

((600, 100, 6), (600, 6))

In [104]:
X_train, X_test, y_train, y_test = train_test_split(dataset, label, random_state=0, test_size=0.3)

X_test.shape

(180, 100, 6)

In [105]:
callback = [
    ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=3, min_lr=0.000001), 
    #ModelCheckpoint(filepath='./weights.h5', save_best_only=True),
    EarlyStopping(monitor='val_acc', restore_best_weights=True, patience=5)
]

In [106]:
K.clear_session()

In [107]:
model_once = Sequential()

model_once.add(LSTM(30, input_shape=(100,6)))
model_once.add(Dense(6, activation='softmax'))
model_once.compile(loss='categorical_crossentropy', optimizer=Adam(lr=0.01), metrics=['acc'])

model_once.fit(X_train, y_train, epochs=30)

Epoch 1/30
420/420 [==============================] - 11s 25ms/step - loss: 1.6232 - acc: 0.2810
Epoch 2/30
420/420 [==============================] - 3s 7ms/step - loss: 1.1530 - acc: 0.5786
Epoch 3/30
420/420 [==============================] - 3s 7ms/step - loss: 1.3260 - acc: 0.5333
Epoch 4/30
420/420 [==============================] - 3s 7ms/step - loss: 1.4118 - acc: 0.4452A: 1s - loss: 1.4939 - acc:
Epoch 5/30
420/420 [==============================] - 3s 6ms/step - loss: 1.0103 - acc: 0.6095A: 1s - loss: 1.0533 - acc: - ETA: 0s - loss: 1.0072 - acc: 0.61
Epoch 6/30
420/420 [==============================] - 3s 7ms/step - loss: 0.8108 - acc: 0.7143
Epoch 7/30
420/420 [==============================] - 3s 7ms/step - loss: 0.7704 - acc: 0.7333
Epoch 8/30
420/420 [==============================] - 3s 7ms/step - loss: 0.7584 - acc: 0.7214
Epoch 9/30
420/420 [==============================] - 3s 7ms/step - loss: 0.5565 - acc: 0.8500
Epoch 10/30
420/420 [==============================]

In [108]:
model_once.evaluate(X_test, y_test)

180/180 [==============================] - 1s 6ms/step


[0.4037811954816182, 0.9277777751286824]

In [34]:
y_test_to_int = np.arange(len(y_test))
x_test_to_int = np.arange(len(X_test)) 

for j in range(len(X_test)):
    x_test_to_int[j] = int(model_once.predict_classes(X_test[j:j+1]))
    for k in range(6):
        if(y_test[j,k] == 1):
            y_test_to_int[j] = k 
            
count=0
print("Real value : Prediction\n---------------------------")
for i in range(len(X_test)):
    if(y_test_to_int[i] != x_test_to_int[i]):
#        print("   ",y_test_to_int[i], "\t   : \t", x_test_to_int[i])
        count = count + 1
probab = count/len(X_test)
print("\n\nNumber of miscalculation : ",count,"/",len(x_test_to_int),"=",round(probab,3))
print("\nAccuracy : ",((1-round(probab,4))*100),"%")

count_0 = 0
count_1=0
count_2 = 0
count_3=0
count_4=0 
count_5 = 0

for m in range(count):
    if (y_test_to_int[m]==0):
        count_0 = count_0 + 1        
    elif (y_test_to_int[m] == 1):
        count_1 = count_1 + 1        
    elif (y_test_to_int[m] == 2):
        count_2 = count_2 + 1        
    elif (y_test_to_int[m] == 3):
        count_3 = count_3 + 1        
    elif (y_test_to_int[m] == 4):
        count_4 = count_4 + 1        
    elif (y_test_to_int[m] == 5):
        count_5 = count_5 + 1   
        
print("\nWrong data_labels_y_value\n0s : ",count_0,"\n1s : ",count_1,"\n2s : ",count_2,"\n3s : ",count_3,"\n4s : ",count_4,"\n5s : ",count_5)

Real value : Prediction
---------------------------


Number of miscalculation :  9 / 180 = 0.05

Accuracy :  95.0 %

Wrong data_labels_y_value
0s :  0 
1s :  1 
2s :  2 
3s :  0 
4s :  4 
5s :  2


In [133]:
test_data_set = pd.read_csv("C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/test_data/RL1.csv",names=['n','na','a','b','c','d','a-b','c-d'])
test_data_set = np.zeros((len(test_data_set), 100, 6))
#test_data_set_LR2
for i, data in enumerate(test_data_set):
    test_data_set[i] = pd.read_csv("C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/test_data/RL1.csv", names=['n','na','a','b','c','d','a-b','c-d']).sample(n=100).sort_index().iloc[:,:6]

#print(test_data_set_LR2)
model_once.predict_classes(test_data_set)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [113]:
model_once.predict_classes(test_data_set).shape

(900,)

In [114]:
len(test_data_set)

900

In [132]:
test_data_set = pd.read_csv("C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/test_data/RL2.csv",names=['n','na','a','b','c','d','a-b','c-d'])
test_data_set = np.zeros((len(test_data_set), 100, 6))
#test_data_set_LR2
for i, data in enumerate(test_data_set):
    test_data_set[i] = pd.read_csv("C:/Users/hml76/OneDrive/바탕 화면/Capacitive_sensor_research/new_datas/datas/test_data/RL2.csv", names=['n','na','a','b','c','d','a-b','c-d']).sample(n=100).sort_index().iloc[:,:6]

#print(test_data_set_LR2)
model_once.predict_classes(test_data_set)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [13]:
### 여기서 신호가 0~5 면 각각 제스처에 따라 0~5로 아두이노로 보내기, 아두이노도 마찬가지, 0~5 받으면 조건문으로 알맞은 창 올리기

import serial

ser = serial.Serial(
    port='COM8',
    baudrate=9600,
)

while True:
    if ser.readable():
        print(ser.read().decode(), end='')

SerialException: could not open port 'COM8': PermissionError(13, '액세스가 거부되었습니다.', None, 5)

In [14]:
print("h")

h


In [ ]:
import serial

#ser = serial.Serial(    port='COM8',    baudrate=9600,)
ser = serial.Serial('COM9',9600)

while(1):
    c = input()
    
    if c=='q':
        break
    else:
        c = c.encode('utf-8')
        ser.write(c)

In [3]:
import serial
print('serial ' + serial.__version__)

# Set a PORT Number & baud rate
PORT = 'COM5'
BaudRate = 9600

ARD= serial.Serial(PORT,BaudRate)

A=1234
B=5678

A=str(A)
B=str(B)
Trans="Q" + A + B
Trans= Trans.encode('utf-8')


while (True):
    ARD.write(Trans)  # Q12345678 전송


serial 3.4


KeyboardInterrupt: 